// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3prp6pUyChIHPjT3hJfUCUIEdJdUO0pU',
    appId: '1:634703648687:android:c944f79a6c051f50b0015a',
    messagingSenderId: '634703648687',
    projectId: 'math-idir',
    databaseURL: 'https://math-idir-default-rtdb.firebaseio.com',
    storageBucket: 'math-idir.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh04tyN1-SBlkaKCx21ZFt7Kw5Notj7Bk',
    appId: '1:634703648687:ios:16602c8763f7643db0015a',
    messagingSenderId: '634703648687',
    projectId: 'math-idir',
    databaseURL: 'https://math-idir-default-rtdb.firebaseio.com',
    storageBucket: 'math-idir.appspot.com',
    androidClientId: '634703648687-dfbmgfi576ka58fjdmmoop762jlfb0e4.apps.googleusercontent.com',
    iosClientId: '634703648687-q2lvokbtp74mnc83chibk718ootdgqjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.zawyaIslamic',
  );
}
